version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: imp-tt-rss
      APP_PORT: 80

  server:
    container_name: tt-rss
    image: lunik1/tt-rss:latest
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure
