version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: imp-pwndrop
      APP_PORT: 8080

  server:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    volumes:
      - ${APP_DATA_DIR}/data/code:/code
    environment:
      - SECRET_PATH=/user
    restart: on-failure
